reports:
    resource: "@ReportsBundle/Controller/"
    type:     annotation
    prefix:   /

lists:
    resource: "@ListsBundle/Controller/"
    type:     annotation
    prefix:   /list

filters:
    resource: "@FiltersBundle/Controller/"
    type:     annotation
    prefix:   /filter

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

entries:
    resource: "@EntriesBundle/Controller/"
    type:     annotation
    prefix:   /entries

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /schedule

layout:
    resource: "@LayoutBundle/Controller/"
    type:     annotation
    prefix:   /layout

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /default

members:
    resource: "@MembersBundle/Controller/"
    type:     annotation
    prefix:   /members

vouchers:
    resource: "@VouchersBundle/Controller/"
    type:     annotation
    prefix:   /vouchers

oneup_uploader:
    resource: .
    type: uploader